# Generated by Django 3.0.6 on 2020-05-18 20:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20200518_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
