# Generated by Django 3.0.6 on 2020-05-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_dashboard_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='theme',
            field=models.CharField(default='theme', max_length=80),
        ),
    ]
