# Generated by Django 3.0.6 on 2020-05-22 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_dashboard_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='user_id',
        ),
    ]
