# Generated by Django 3.0.6 on 2020-06-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_remove_dashboard_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
