# Generated by Django 3.0.6 on 2020-06-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_dashboard_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='private',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
