FROM python:3.8

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r  /usr/src/app/requirements.txt



COPY . /usr/src/app/
COPY ./entrypoint.sh entrypoint.sh
RUN chmod +x  entrypoint.sh

# run entrypoint.sh
# ENTRYPOINT ["bash", "entrypoint.sh"]
